### ISSUE TITLE
Move to CCG

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/webkms#3]
https://github.com/w3c-ccg/webkms/issues/1

Not sure how this should be done, but I'm eager to make progress on WebKMS, especially after understanding how it will integrate with Encrypted Data Vaults.

Do I have permission to import the current spec into the CCG?

Will we be archiving or marking this repo as read only once it is moved?

**Comment by OR13** [comment]
Blocked by:
- https://github.com/digitalbazaar/webkms/pull/2
- https://github.com/digitalbazaar/webkms/pull/4

**Comment by OR13** [comment]
@dlongley happy to help with stuff however I can.

**Comment by dmitrizagidulin** [comment]
(In the process of moving this repo to the CCG)

**Comment by dmitrizagidulin** [comment]
@OR13 transferred! (I don't have write access to this repo, otherwise I'd close the issue :) )

**Comment by OR13** [comment]
@dmitrizagidulin I got u :)
